### ISSUE TITLE
Default.aspx

### ISSUE THREAD

**Issue by sorenfisker** [dadorner-msft/ActivationWs#1]
Default.aspx references nonexisting file default.aspx.cs

**Comment by dadorner-msft** [comment]
Hello @sorenfisker, thank you for reaching out! I have uploaded the requested file. Please let me know if the issue can be closed. Should you have any questions please do not hesitate to contact me.

**Comment by sorenfisker** [comment]
Fails with "Could not load type 'ActivationWs.WebForm'." in line 1

**Comment by dadorner-msft** [comment]
Hi @sorenfisker , what were the steps that you took before this issue occurred?

**Comment by sorenfisker** [comment]
This is working in v. 17.0 release.
