### ISSUE TITLE
Need help to get it setup in IIS

### ISSUE THREAD

**Issue by MaikGDE** [dadorner-msft/ActivationWs#10]
Hello Daniel,

unfortunately I do lack experience to set this up in IIS. 

IIS itself seems to be OK since I can browse to the server itself using http but apart of the metioned .Net and ASP.net requirements, could you share some more details how to actually add the website (really as website, or application ?) 
What application pool has to be used ? 
Anything additional to consider when adding the roles and features ? 

Running on Server 2012 r2 / .net 4.8 is installed, HTTP activation and ASP.NET 4.5 is present, using latest v018.1 release. 

Any feedback appreciated

Thanks
Maik

**Comment by dadorner-msft** [comment]
Hello Maik, 

Thank you for your patience! Below you will find the steps to conclude the installation.

**Install the IIS role and features**
1. Open Server Manager and click Add Roles and Features
2. On the Server Roles page, select Web Server (IIS) 
3. Click Next till the Web Server Role (IIS) page is displayed
4. Under Application Development, select ASP.NET 4.7 
5. Click Next until you have completed the wizard

**Set up the ApplicationWs web service**

1. Download the latest ActivationWs release and extract it (eg. C:\inetpub\wwwroot\ActivationWs). The folder structure should look like this:

Directory: C:\inetpub\wwwroot\ActivationWs

    Name
    ----
    bin
    Scripts
    ActivationWs.asmx
    Default.aspx
    Web.config

2. Specify a proxy server in the web.config file where necessary
3. Open Internet Information Services (IIS) Manager
4. Add a new website. Select .NET v4.5 as application pool
5. Browse to the ActivationWs website, it should be loaded without an error

Best regards,
Daniel

**Comment by dadorner-msft** [comment]
Hello Maik,
Did it work out or do you need further assistance? A quick update would be great.
Thank you,
Daniel

**Comment by Stuzv** [comment]
Hi Daniel,

Just to be certain as we are just deploying our iis servers, there is no dependence on the folder structure & names is there e.g. e:\iis\ActivationWS is fine instead of c:\inetpub\wwwroot?

Also would you happen to have a list of known error codes being returned to the activating server or are they just standard IE int errors

**Comment by dadorner-msft** [comment]
Hello @Stuzv,
It's not obligatory to deploy ActivationWs to the 'C:\inetpub\wwwroot\ActivationWs' directory. For the error codes, please take a look at the source code. You may also want to deploy the latest version to make use of all features, including the revised error handling.
This issue would be closed.
