### ISSUE TITLE
Issue activating 

### ISSUE THREAD

**Issue by Stuzv** [dadorner-msft/ActivationWs#12]
Hi Daniel,
Got this issue just come up wondered if you could offer some help with it?

Trying to activate through our proxy now returns this error

__The Confirmation ID could not be retrieved (Exception calling 'CreateWebRequest': The remote name could not be resolved: 'activation.sls.microsoft.com')__

Proxy team + locally using netstat on the IIS server we cannot see any connection being made to the proxy

web.config for proxy is

    <defaultProxy>
      <proxy 
        usesystemdefault="True" 
        proxyaddress="https://10.239.9.190:443" 
        bypassonlocal="True"
      />
      <bypasslist>
        <add address="[a-z]+\.contoso\.com$" />
      </bypasslist>
    </defaultProxy>
  -->

The IIS server can access  https://activation.sls.microsoft.com/slspc/SLActivate.asmx through the same proxy server within the browser 

Any know bug or fault finding you can advise me on at all please

Stu

**Comment by dadorner-msft** [comment]
Hello Stu,
Remove the <-- and --> chars from your web.config file, restart the site and try again.

Regards,
Daniel

**Comment by Stuzv** [comment]
omg fsu layer 8 issue, many thanks -Stu
