### ISSUE TITLE
BatchActivation service down?

### ISSUE THREAD

**Issue by 4var1** [dadorner-msft/ActivationWs#14]
Hi - we've used your excellent WS to activate many thousands of systems - thanks for your hard work. Apologies for opening this issue as it doesn't look to be a problem with ActivationWS itself - but it is related.

We have hit an issue this year as we deploy keys for 2021 - and we're trying to troubleshoot it. 

ActivationWS is running fine - but returns error 500 when we try to activate keys. First step is to check access to the MS URLs.

When we test connectivity to https://activation.sls.microsoft.com/BatchActivation/BatchActivation.asmx - the service appears down - get the generic error shown below. We've tested outside a proxy and it's the same result.

Is anyone else having issues? We are pretty sure this worked for us before the weekend of 16th Jan 2021. We're also going to log a ticket with Microsoft.

Server Error in '/BatchActivation' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

**Comment by dadorner-msft** [comment]
Hello @4var1 , thank you for reaching out! I just checked the service and could not reproduce any issues. I would recommend to update to release [v.0.19.0](https://github.com/dadorner-msft/ActivationWs/releases/tag/v0.19.0). Please let me know if that works!

Thank you for believing in ActivationWs, stay healthy!

Best regards,
Daniel

**Comment by 4var1** [comment]
My apologies - we've discovered that our license provider didn't increase activation limit on our Year 2 keys - they added them to the Year 1 keys. Updating to the latest version of ActivationWS showed the activation limit exceeded rather than just the 500 error - so all good. Thanks for your time and support. Closing case!
