### ISSUE TITLE
Unable to retrieve Year 1 ESU Confirmation ID

### ISSUE THREAD

**Issue by raphson93** [dadorner-msft/ActivationWs#15]
![image](https://user-images.githubusercontent.com/19220265/105436289-eebc4680-5c99-11eb-8d51-755df8e46dc8.png)

I was unable to retrieve the confirmation id.
Does it mean I can no longer activate win 7 esu after 14 January 2021?

**Comment by dadorner-msft** [comment]
Hello @raphson93 , your screenshot shows that the product key has been blocked. Please contact your reseller/service provider/Microsoft to get this sorted out.

Best regards,
Daniel
