### ISSUE TITLE
Missing Releases

### ISSUE THREAD

**Issue by KevinFumbles** [dadorner-msft/ActivationWs#16]
In the README, it mentions grabbing the latest compiled version from the [releases](https://github.com/dadorner-msft/ActivationWs/releases), but there are currently no releases available. Could you push one out, or perhaps teach me how to compile the source code myself?

Thanks

**Comment by dadorner-msft** [comment]
Hi @KevinFumbles ,
I am not allowed to publish new releases through this channel. Please reach out to your Microsoft representative to obtain the latest release.

Best regards,
Daniel
