### ISSUE TITLE
Windows 7 Year 2 ESU Activation error

### ISSUE THREAD

**Issue by Naveen-kanneganti** [dadorner-msft/ActivationWs#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
We have started to receive errors during the licencing of our year 2 ESU licence key.  
The key was working correctly, and the activation server was responding correctly.  The key installs correctly on the client, but we are now seeing a server error (error 500) when a client attempts to activate the license from the activation server.   other products (a server key for example) can activate correctly.

any suggestions ?

 log files:
09/09/2021 12:13:49; Installing product key 8kp5r ...
09/09/2021 12:14:06; Retrieving license information...
09/09/2021 12:14:06; Name             : Windows(R) 7, Client-ESU-Year2 add-on for EnterprierpriseE,EnterpriseN,Professional,ProfessionalE,ProfessionalN,Ultimate,UltimateE,UltimateN
09/09/2021 12:14:06; Installation ID  : 03256283667543173696075556398485xxxxxxxx
09/09/2021 12:14:06; Activation ID    : 0b00a45b-8643-2acxxxx
09/09/2021 12:14:06; Extd. Product ID : 33052-00166-432-066778-02-1068-6502.0000-xxx
09/09/2021 12:14:06; Sending an activation request to http://esulxxx:1689/ActivationWs/ActivationWs.asmx...
09/09/2021 12:14:07; [Warning] The remote server returned an error: (500) Internal Server Error.
09/09/2021 12:14:07; Connection to web service will be retried in 30 seconds (1/5)...
09/09/2021 12:14:37; [Warning] The remote server returned an error: (500) Internal Server Error.
09/09/2021 12:14:37; Connection to web service will be retried in 30 seconds (2/5)...
09/09/2021 12:15:54; [Warning] The remote server returned an error: (500) Internal Server Error.
09/09/2021 12:15:54; Connection to web service will be retried in 30 seconds (3/5)...
09/09/2021 12:16:25; [Warning] The remote server returned an error: (500) Internal Server Error.
09/09/2021 12:16:25; Connection to web service will be retried in 30 seconds (4/5)...
09/09/2021 12:16:55; [Warning] The remote server returned an error: (500) Internal Server Error.
09/09/2021 12:16:55; Connection to web service will be retried in 30 seconds (5/5)...
09/09/2021 12:17:26; [Warning] The remote server returned an error: (500) Internal Server Error.
09/09/2021 12:17:26; [Error] Number of maximum connection retries reached. The execution of this script will be stopped

**Comment by dadorner-msft** [comment]
Hi @Naveen-kanneganti,
Please update ActivationWs to the latest version, then everything should work as expected.

Best regards,
Daniel
