### ISSUE TITLE
ESU Webserver not working!

### ISSUE THREAD

**Issue by zakhanaus** [dadorner-msft/activationws#19]
Hi Team 

I have downloaded the entire Src folder and created a webserver website on server 2019 IIS, but its failing to open link with the below error.

 
![image](https://github.com/dadorner-msft/activationws/assets/44820973/e9b83681-5d9f-412e-90a7-430f18e32fd7)

![image](https://github.com/dadorner-msft/activationws/assets/44820973/255f9aa9-5023-437f-be7d-c6e3f9e22d50)

Source c:\inetpub\wwwroot\AtivationWs\web.config line 28

If I remove this line from web.config then I get another error.

Thanks in advance for your help.

**Comment by dadorner-msft** [comment]
Hello @zakhanaus, thank you for reaching out! The source code cannot be executed natively on your computer, it has to be compiled. If you do not want to compile your own version, please reach out to your Microsoft representative or feel free to contact me.

**Comment by zakhanaus** [comment]
Hello @dadorner-msft Thank you for your prompt response. I am happy to compile it, but do we have a guide on how to do it?

**Comment by dadorner-msft** [comment]
You can use the Visual Studio IDE to build an application. Please take a look at the following article: https://learn.microsoft.com/en-us/visualstudio/ide/compiling-and-building-in-visual-studio?view=vs-2022

**Comment by zakhanaus** [comment]
Hi @dadorner-msft - Thank you for sharing the solution. I was able to create the solution using VS ISE.
