### ISSUE TITLE
Exception calling 'CallWebService'

### ISSUE THREAD

**Issue by StadtBadWurzach** [dadorner-msft/ActivationWs#2]
**Describe the bug**
I execute the powershell script as local administrator. In my test vm running windows 7 professional (x64, sp1) with the latest windows updates.
My command:
`.\Activate-Product.ps1 -ProductKey abcde-fghij-qwert-poiuz-mnbvc -WebServiceUrl http://msesu.domain.de:80`

Here the output of the powershell console:
[errorlog.txt](https://github.com/dadorner-msft/ActivationWs/files/4218328/errorlog.txt)

Here the powershell information of the test client:
Name             : ConsoleHost
Version          : 3.0
InstanceId       : ca7cc54f-b3e7-4c4e-b5ba-ccf914da6d79
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : de-DE
CurrentUICulture : de-DE
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

The Update kb4538483 was successfully installed on the client. The http call (https://msesu.domain .de/Default.aspx) on the client was successfully. I can enter the  Installation ID and Extended PID and get the conformation id.

**Screenshots**
![Activate-Product-error-output-step02](https://user-images.githubusercontent.com/43094829/74721476-baddd300-5237-11ea-8b6c-a6cc0c5e5f64.png)
![Activate-Product-error-output-step01](https://user-images.githubusercontent.com/43094829/74721471-b9140f80-5237-11ea-8ea6-9674a1eb65f6.png)

**Additional context**
ActivationWs is installed on windows server 2012r2 standard (x64, sp1, latest windows updates). Both machines (server and client) are installed in german language.

Regards

**Comment by dadorner-msft** [comment]
Hello,

Thank you for reaching out! Please change the value of the WebServiceUrl parameter to `http://msesu.domain.de:80/activationws.asmx`.

Please let me know if the issue can be closed. Should you have any questions please do not hesitate to contact me.

Best regards,
Daniel

**Comment by StadtBadWurzach** [comment]
Hello Daniel,
arrr... you are right.
Now it works as it should. :+1: 


Regards,
Daniel
