### ISSUE TITLE
Microsoft.CodeDom.Providers.DotNetCompilerPlatform could not be located

### ISSUE THREAD

**Issue by skywalkerr6** [dadorner-msft/activationws#20]
Getting the below error after extracting the source files in IIS folder. Could you please let me know how can fix it? I have never used visual studio before. We need this to setup the MAK ESU activation for Windows 2012 R2. Thank you.

Server Error in '/' Application.
Configuration Error
Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately.

Parser Error Message: The CodeDom provider type "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be located.

Source Error:

Line 26:   <system.codedom>
Line 27:     <compilers>
Line 28:       <compiler extension=".cs" language="c#;cs;csharp" warningLevel="4" compilerOptions="/langversion:7.0 /nowarn:1659;1699;1701;612;618" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
Line 29:       <compiler extension=".vb" language="vb;vbs;visualbasic;vbscript" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008,40000,40008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
Line 30:     </compilers>

Source File: C:\inetpub\activationws-0.25.1\src\web-service\aspnet\ActivationWs\web.config    Line: 28

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.9206.0

**Comment by dadorner-msft** [comment]
Hi @skywalkerr6, thank you for reaching out! The source code cannot be executed natively on your computer; it has to be compiled. Please take a look at #19 for further information.
