### ISSUE TITLE
IIS Web Site Error

### ISSUE THREAD

**Issue by sni07** [dadorner-msft/ActivationWs#3]
Hi,

i get an eror while browsing the activation Website. Can anyone help?

Server Error in'/' Application 
Configuration Error

Parser Error Message: The CodeDom provider type "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be located

Line 28:       <compiler language="c#;cs;csharp" extension=".cs"

regards

**Comment by StadtBadWurzach** [comment]
Do you had installed ASP.NET 3.5 or 4.5 and .net Framework 4.6 or higher on the server?

**Comment by sni07** [comment]
Windows Server 2012R2
IIS 8.5
.Net 4.6, ASP 4.0.30319

**Comment by DanielSimonWe** [comment]
Are all .cs Files in the same directory? And have you activated the HTTP-Activation Feature on your IIS?

**Comment by sni07** [comment]
are files are in the same directory and the http feature is installed. On an Windows 2019 Server i have the same problem.

**Comment by dadorner-msft** [comment]
Hello @sni07 , 
What were the steps that you took to deploy the web service? Did you deploy the content of the ZIP file (https://github.com/dadorner-msft/ActivationWs/releases/download/v.0.17.0/Release_v0.17.0.zip) or the content of the src folder to IIS?
Best regards,
Daniel

**Comment by sni07** [comment]
Hi Daniel,
I only deployed the src folder to IIS.

regards
Sven

**Comment by dadorner-msft** [comment]
Hello Sven,
Thank you for your update! Please deploy the latest release (https://github.com/dadorner-msft/ActivationWs/releases/download/v.0.17.0/Release_v0.17.0.zip) to IIS. Should you have any questions please do not hesitate to contact me.
Best regards,
Daniel

**Comment by sni07** [comment]
Thank you very much for your quick help, it works now.

best regards,

Sven

**Comment by Bibi74** [comment]
Hi Daniel,

I have the same issue even after downloading and deploying the src folder from https://github.com/dadorner-msft/ActivationWs/releases/download/v.0.17.0/Release_v0.17.0.zip.

in Source File web.config    Line:  28 "

Can you help please.
Thanks.
Regards,
Al
