### ISSUE TITLE
Confirmation ID could not be retrieved (0x67)

### ISSUE THREAD

**Issue by pat33fr** [dadorner-msft/ActivationWs#4]
Hy,
I'm trying to use "ActivationWs"
I'm using a proxy so i've modified web.config file like this

<?xml version="1.0" encoding="utf-8"?>

<configuration>
  <system.web>
    <compilation targetFramework="4.6" />
    <httpRuntime targetFramework="4.6" />
  </system.web>
  <system.net>
    <defaultProxy>
      <proxy 
        usesystemdefault="False"
        proxyaddress="http://RealProxyName:8181"
        bypassonlocal="False"
      />
    </defaultProxy>
  </system.net>
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
</configuration>

To try the activation process manually, i access my url : http://WebServer/ActivationWs/
Then enter an Installation ID and en Extended PID then click "Submit" button

I keep getting this error : 
The Confirmation ID could not be retrieved (Exception calling 'ParseSoapResponse': The Confirmation ID could not be retrieved (0x67))

Can you help me please ?

**Comment by pat33fr** [comment]
web.config : 
      <proxy 
        usesystemdefault="False"
        proxyaddress="http://surf-lbr.com1.intra.laposte.fr:8080"
        bypassonlocal="False"
      />

**Comment by pat33fr** [comment]
I think i Don't have all the KB needed before installing ESU MAK Key.
I'll first check this and come back to you.
Sorry for that…

**Comment by dadorner-msft** [comment]
Hello @pat33fr ,
No worries about that! Your site successfully connected to the Batch Activation Service. Please ensure that the Installation ID and Extended Product ID are correct and try retrieve the Confirmation ID again.
Best regards,
Daniel

**Comment by pat33fr** [comment]
Hy,
I've juste finished my tests and finally all is working !
I've installed all the KB listed here :
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/obtaining-extended-security-updates-for-eligible-windows-devices/ba-p/1167091

And then, all goes fine.

Sorry for this inconvenience and thanks a lot for your tool.

**Comment by dadorner-msft** [comment]
Hello @pat33fr,
Thank you for your update, glad to hear that it works now. Should you have any further questions, please feel free to reach out.
Take care of yourself,
Daniel
