### ISSUE TITLE
Help please :(

### ISSUE THREAD

**Issue by craigss0** [dadorner-msft/ActivationWs#5]
Hi, 
Thanks for producing the tool seems to be a more modern way other than using VAMT.

I have received a few errors back when using the manual  "ActivationWs" via the IIS webserver i have setup. 

I keep getting this errors below :
The Confirmation ID could not be retrieved (Exception calling 'ParseSoapResponse': The Confirmation ID could not be retrieved (0x67))

The Confirmation ID could not be retrieved (0x80131600)
   at ActivationWs.ActivationHelper.ParseSoapResponse(XmlDocument soapResponse) in C:\Users\dadorner\source\repos\ActivationWs\ActivationWs\Activation.cs:line
 
Please could you provide any documentation you have on the error codes returned or advice on resolving these errors i am receiving. 

Thanks 
Craigss0

**Comment by dadorner-msft** [comment]
Hello @craigss0 ,
I unfortunately can't provide you with any of those information. Do double check that the Installation- and Extended Product ID are correct, that's often the root of the problem. Please also take a look at #4 , it might be of help.

Best regards,
Daniel

**Comment by dadorner-msft** [comment]
Hi @craigss0 ,
Did it work out or do you need further assistance? A quick update would be great.
Thank you and stay safe,
Daniel

**Comment by dadorner-msft** [comment]
Issue closed due to inactivity.
