### ISSUE TITLE
ActivaeWS

### ISSUE THREAD

**Issue by araboglos** [dadorner-msft/ActivationWs#6]
Hi,

I am having issues getting ActivateWS working.  I am getting error Exception calling 'CreateWebRequest': Unable to connect to the remote server 

I am trying to Manual Confirm ID retrieval.

I have whit listed https://activation.sls.microsoft.com

Is there any other URLS that need to be white listed?

Manual Confirmation ID retrieval

Any help would be wonderful

Thanks
Greg
![Capture](https://user-images.githubusercontent.com/63269820/78617713-4a187600-78cc-11ea-9bb7-61d925384008.JPG)

**Comment by dadorner-msft** [comment]
Hello Greg,
Please specify a proxy server in the web.config file and restart the site in IIS.
Best regards,
Daniel

**Comment by araboglos** [comment]
Thanks for your response, I have added the proxy server  in the web.config but still the same issue

**Comment by araboglos** [comment]
Hi,
Webcongig details

**Comment by dadorner-msft** [comment]
Hello Greg,

Please confirm that you did uncomment the defaultProxy element (by removing the <-- and --> characters) in the web.config file. Also verify that you can resolve the hostname of the proxy (alternatively try to use its IP address) and restart the site in IIS. If all of that did not work, check that the [whitelisted URL](https://github.com/dadorner-msft/ActivationWs#requirements). If your proxy requires user authentication (username/password), you will have to build a custom web service. Do not hesitate to [contact me](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fdadorner-msft) if you should have any questions. 

I am looking forward to hear from you,
Daniel

**Comment by dadorner-msft** [comment]
Hello Greg,
Did it work out or do you need further assistance? A quick update would be great.
Looking forward to hear from you!
Daniel

**Comment by araboglos** [comment]
Thank you very much for your help, it was a proxy issue, my issue has been resolved. I just need to deploy the pre req windows updates and deploy the script.
