### ISSUE TITLE
Activation process through NAT

### ISSUE THREAD

**Issue by pat33fr** [dadorner-msft/ActivationWs#7]
I just have a question, it's not a problem.
I have some workstations/servers that must do NAT to access the URL of the IIS Server for activation.
I think it will work but can you confirm this, please ?
Thanks a lot again.

**Comment by dadorner-msft** [comment]
Hi there, I can unfortunately not give you a confirmation without any insights to your system. No harm trying it out, then you will have an answer if it works or not. Good luck!
