### ISSUE TITLE
[Error] Exception calling 'CallWebService': Exception calling "Create" with "1" argument(s): "Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section."

### ISSUE THREAD

**Issue by slawrensen** [dadorner-msft/ActivationWs#8]
When running the script I get the below error output in the log:

5/22/2020 12:13:59 PM; [Error] Exception calling 'CallWebService': Exception calling "Create" with "1" argument(s): "Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section."

**Comment by dadorner-msft** [comment]
Hello! Please check the defaultProxy element for errors, the proxyaddress attribute may contain an invalid value. If that should not be the case, please upload your web.config file.

Best regards,
Daniel
